import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

/* ========= 新增：后端基址解析，优先同源 /proxy，次选 LAN:3001 ========= */
function getBackendBase(): { type: 'same-origin' | 'absolute', base: string } {
  // 1) 显式配置优先（可选）：在 .env 里设置 VITE_BACKEND_BASE，例如：
  //    http://192.168.x.x:3001 或 https://your-domain/proxy
  //    线上反向代理时尤其好用
  // @ts-ignore
  const envBase = import.meta?.env?.VITE_BACKEND_BASE as string | undefined;
  if (envBase && envBase.trim()) {
    // 允许既可以是绝对地址（http://ip:3001），也可以是相对路径（/proxy）
    if (envBase.startsWith('/')) return { type: 'same-origin', base: envBase.replace(/\/+$/, '') };
    return { type: 'absolute', base: envBase.replace(/\/+$/, '') };
  }

  // 2) 如果当前页面是 HTTPS，浏览器会拦截去 http://ip:3001 的明文请求（混合内容）。
  //    这时 *必须* 用同源路径 `/proxy`（交由 Vite 或反向代理转发到后端）。
  if (window.location.protocol === 'https:') {
    return { type: 'same-origin', base: '/proxy' };
  }

  // 3) 其余情况（页面是 http），可以直接访问同一主机的 3001 端口，
  //    这样本机打开是 localhost:3001，局域网其他设备打开你的前端页面时也会走 <你的局域网IP>:3001
  const host = window.location.hostname; // 可能是 localhost、127.0.0.1、192.168.x.x、机器名等
  return { type: 'absolute', base: `http://${host}:3001` };
}

export function getApiBaseUrl(): string {
  const { type, base } = getBackendBase();
  return type === 'same-origin' ? base : `${base}`;
}

export async function apiPost<T>(path: string, body?: any): Promise<T> {
  const url = `${getApiBaseUrl()}${path}`;
  const resp = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
  return resp.json();
}

export async function apiGet<T>(path: string, params?: Record<string, string>): Promise<T> {
  const u = new URL(`${getApiBaseUrl()}${path}`, window.location.origin);
  if (params) Object.entries(params).forEach(([k, v]) => u.searchParams.set(k, v));
  const resp = await fetch(u.toString(), { method: 'GET' });
  if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
  return resp.json();
}

// CSV解析函数
export const parseCSV = (csvString: string): Record<string, any>[] => {
  const lines = csvString.trim().split('\n');
  const headers = lines[0].split(',').map(header => header.trim());
  return lines.slice(1).map(line => {
    const values = line.split(',').map(value => value.trim());
    return headers.reduce((obj, header, index) => {
      obj[header] = values[index] || '';
      return obj;
    }, {} as Record<string, any>);
  });
};

// 国家ID数据 (从CSV文件导入)
export const countryIdData = [
  { country_id: "1", Country: "Andorra" },
  { country_id: "2", Country: "Afghanistan" },
  { country_id: "3", Country: "Anguilla" },
  { country_id: "4", Country: "Angola" },
  { country_id: "5", Country: "Antarctica" },
  { country_id: "6", Country: "Aruba" },
  { country_id: "7", Country: "Barbados" },
  { country_id: "8", Country: "Bangladesh" },
  { country_id: "9", Country: "Burkina Faso" },
  { country_id: "10", Country: "Burundi" },
  { country_id: "11", Country: "Benin" },
  { country_id: "12", Country: "Bermuda" },
  { country_id: "13", Country: "Brunei Darussalam" },
  { country_id: "14", Country: "Bolivia" },
  { country_id: "15", Country: "Bhutan" },
  { country_id: "16", Country: "Botswana" },
  { country_id: "17", Country: "Belarus" },
  { country_id: "18", Country: "Belize" },
  { country_id: "19", Country: "Canada" },
  { country_id: "20", Country: "China" },
  { country_id: "21", Country: "Colombia" },
  { country_id: "22", Country: "Costa Rica" },
  { country_id: "23", Country: "Cuba" },
  { country_id: "24", Country: "Cyprus" },
  { country_id: "25", Country: "Djibouti" },
  { country_id: "26", Country: "Dominica" },
  { country_id: "27", Country: "Ecuador" },
  { country_id: "28", Country: "Eritrea" },
  { country_id: "29", Country: "Finland" },
  { country_id: "30", Country: "Fiji" },
  { country_id: "31", Country: "France" },
  { country_id: "32", Country: "Gabon" },
  { country_id: "33", Country: "Grenada" },
  { country_id: "34", Country: "Guernsey" },
  { country_id: "35", Country: "Ghana" },
  { country_id: "36", Country: "Gibraltar" },
  { country_id: "37", Country: "Gambia" },
  { country_id: "38", Country: "Guinea" },
  { country_id: "39", Country: "Guadeloupe" },
  { country_id: "40", Country: "Guatemala" },
  { country_id: "41", Country: "Guam" },
  { country_id: "42", Country: "Guyana" },
  { country_id: "43", Country: "Honduras" },
  { country_id: "44", Country: "India" },
  { country_id: "45", Country: "Iran" },
  { country_id: "46", Country: "Jersey" },
  { country_id: "47", Country: "Jamaica" },
  { country_id: "48", Country: "Japan" },
  { country_id: "49", Country: "Kiribati" },
  { country_id: "50", Country: "Laos (Lao People's Democratic Republic)" },
  { country_id: "51", Country: "Saint Lucia" },
  { country_id: "52", Country: "Liechtenstein" },
  { country_id: "53", Country: "Sri Lanka" },
  { country_id: "54", Country: "Liberia" },
  { country_id: "55", Country: "Lesotho" },
  { country_id: "56", Country: "Monaco" },
  { country_id: "57", Country: "Montenegro" },
  { country_id: "58", Country: "Mali" },
  { country_id: "59", Country: "Martinique" },
  { country_id: "60", Country: "Montserrat" },
  { country_id: "61", Country: "Malta" },
  { country_id: "62", Country: "Mauritius" },
  { country_id: "63", Country: "Malawi" },
  { country_id: "64", Country: "Mexico" },
  { country_id: "65", Country: "Mozambique" },
  { country_id: "66", Country: "Niger" },
  { country_id: "67", Country: "Nigeria" },
  { country_id: "68", Country: "Nicaragua" },
  { country_id: "69", Country: "Nepal" },
  { country_id: "70", Country: "Nauru" },
  { country_id: "71", Country: "Niue" },
  { country_id: "72", Country: "Oman" },
  { country_id: "73", Country: "Panama" },
  { country_id: "74", Country: "Peru" },
  { country_id: "75", Country: "Pakistan" },
  { country_id: "76", Country: "Puerto Rico" },
  { country_id: "77", Country: "Portugal" },
  { country_id: "78", Country: "Palau" },
  { country_id: "79", Country: "Paraguay" },
  { country_id: "80", Country: "Qatar" },
  { country_id: "81", Country: "Reunion" },
  { country_id: "82", Country: "Rwanda" },
  { country_id: "83", Country: "Singapore" },
  { country_id: "84", Country: "St. Helena, Ascension and Tristan da Cunha" },
  { country_id: "85", Country: "Sierra Leone" },
  { country_id: "86", Country: "San Marino" },
  { country_id: "87", Country: "Senegal" },
  { country_id: "88", Country: "Suriname" },
  { country_id: "89", Country: "El Salvador" },
  { country_id: "90", Country: "Togo" },
  { country_id: "91", Country: "Thailand" },
  { country_id: "92", Country: "Tokelau" },
  { country_id: "93", Country: "Turkmenistan" },
  { country_id: "94", Country: "Tonga" },
  { country_id: "95", Country: "Tuvalu" },
  { country_id: "96", Country: "Taiwan" },
  { country_id: "97", Country: "Tanzania (United Republic of Tanzania)" },
  { country_id: "98", Country: "Uruguay" },
  { country_id: "99", Country: "Venezuela" },
  { country_id: "100", Country: "Vanuatu" },
  { country_id: "101", Country: "Samoa" },
  { country_id: "102", Country: "Kosovo" },
  { country_id: "103", Country: "Mayotte" },
  { country_id: "104", Country: "Zambia" },
  { country_id: "105", Country: "Zimbabwe" },
  { country_id: "106", Country: "Albania" },
  { country_id: "107", Country: "Algeria" },
  { country_id: "108", Country: "American Samoa" },
  { country_id: "109", Country: "Antigua & Barbuda" },
  { country_id: "110", Country: "Argentina" },
  { country_id: "111", Country: "Armenia" },
  { country_id: "112", Country: "Australia" },
  { country_id: "113", Country: "Austria" },
  { country_id: "114", Country: "Azerbaijan" },
  { country_id: "115", Country: "Bahama's" },
  { country_id: "116", Country: "Bahrain" },
  { country_id: "117", Country: "Belgium" },
  { country_id: "118", Country: "Bonaire, St Eustatius & Saba" },
  { country_id: "119", Country: "Bosnia and Herzegovina" },
  { country_id: "120", Country: "Bouvet Island" },
  { country_id: "121", Country: "Brazil" },
  { country_id: "122", Country: "Bulgaria" },
  { country_id: "123", Country: "Cambodia" },
  { country_id: "124", Country: "Cameroon" },
  { country_id: "125", Country: "Cape Verde" },
  { country_id: "126", Country: "Cayman Islands" },
  { country_id: "127", Country: "Central African Republic" },
  { country_id: "128", Country: "Chad" },
  { country_id: "129", Country: "Chile" },
  { country_id: "130", Country: "Christmas Island" },
  { country_id: "131", Country: "Cocos (Keeling Islands)" },
  { country_id: "132", Country: "Comoros" },
  { country_id: "133", Country: "Congo (Democratic Republic of the Congo)" },
  { country_id: "134", Country: "Congo (Republic of the Congo)" },
  { country_id: "135", Country: "Cook Islands" },
  { country_id: "136", Country: "Cote D'Ivoire (Ivory Coast)" },
  { country_id: "137", Country: "Croatia" },
  { country_id: "138", Country: "Curaçao" },
  { country_id: "139", Country: "Czech Republic" },
  { country_id: "140", Country: "Denmark" },
  { country_id: "141", Country: "Dominican Republic" },
  { country_id: "142", Country: "Timor Leste" },
  { country_id: "143", Country: "Egypt" },
  { country_id: "144", Country: "Equatorial Guinea" },
  { country_id: "145", Country: "Estonia" },
  { country_id: "146", Country: "Ethiopia" },
  { country_id: "147", Country: "Falkland Islands (Malvinas)" },
  { country_id: "148", Country: "Faroe Islands" },
  { country_id: "149", Country: "French Guiana" },
  { country_id: "150", Country: "French Polynesia" },
  { country_id: "151", Country: "Georgia" },
  { country_id: "152", Country: "Germany" },
  { country_id: "153", Country: "Greece" },
  { country_id: "154", Country: "Greenland" },
  { country_id: "155", Country: "Guinea-Bissau" },
  { country_id: "156", Country: "Haïti" },
  { country_id: "157", Country: "Heard & McDonald Islands" },
  { country_id: "158", Country: "Hong Kong" },
  { country_id: "159", Country: "Hungary" },
  { country_id: "160", Country: "Iceland" },
  { country_id: "161", Country: "Indonesia" },
  { country_id: "162", Country: "Iraq" },
  { country_id: "163", Country: "Ireland" },
  { country_id: "164", Country: "Isle of Man" },
  { country_id: "165", Country: "Israel" },
  { country_id: "166", Country: "Italy" },
  { country_id: "167", Country: "Jordan" },
  { country_id: "168", Country: "Kazakhstan" },
  { country_id: "169", Country: "Kenya" },
  { country_id: "170", Country: "Korea (North)" },
  { country_id: "171", Country: "Korea (South)" },
  { country_id: "172", Country: "Kuwait" },
  { country_id: "173", Country: "Kyrgyzstan (Kyrgyz Republic)" },
  { country_id: "174", Country: "Latvia" },
  { country_id: "175", Country: "Lebanon" },
  { country_id: "176", Country: "Libya" },
  { country_id: "177", Country: "Lithuania" },
  { country_id: "178", Country: "Luxembourg" },
  { country_id: "179", Country: "Macau" },
  { country_id: "180", Country: "North Macedonia" },
  { country_id: "181", Country: "Madagascar" },
  { country_id: "182", Country: "Malaysia" },
  { country_id: "183", Country: "Maldives" },
  { country_id: "184", Country: "Marshall Islands" },
  { country_id: "185", Country: "Mauritania" },
  { country_id: "186", Country: "Micronesia" },
  { country_id: "187", Country: "Moldova" },
  { country_id: "188", Country: "Mongolia" },
  { country_id: "189", Country: "Morocco" },
  { country_id: "190", Country: "Myanmar" },
  { country_id: "191", Country: "Namibia" },
  { country_id: "192", Country: "The Netherlands" },
  { country_id: "193", Country: "New Caledonia" },
  { country_id: "194", Country: "New Zealand" },
  { country_id: "195", Country: "Norfolk Island" },
  { country_id: "196", Country: "Northern Mariana Islands" },
  { country_id: "197", Country: "Norway" },
  { country_id: "198", Country: "Palestine" },
  { country_id: "199", Country: "Papua New Guinea" },
  { country_id: "200", Country: "Philippines" },
  { country_id: "201", Country: "Pitcairn" },
  { country_id: "202", Country: "Poland" },
  { country_id: "203", Country: "Romania" },
  { country_id: "204", Country: "Russian Federation (Russia)" },
  { country_id: "205", Country: "South Georgia & South Sandwich Islands" },
  { country_id: "206", Country: "Saint Kitts and Nevis" },
  { country_id: "207", Country: "Saint Martin (Dutch part)" },
  { country_id: "208", Country: "Saint Martin (French part)" },
  { country_id: "209", Country: "Saint Vincent and The Grenadines" },
  { country_id: "210", Country: "Saint-Barthélemy" },
  { country_id: "211", Country: "São Tomé & Principe" },
  { country_id: "212", Country: "Saudi Arabia" },
  { country_id: "213", Country: "Serbia" },
  { country_id: "214", Country: "Seychelles" },
  { country_id: "215", Country: "Slovakia (Slovak Republic)" },
  { country_id: "216", Country: "Slovenia" },
  { country_id: "217", Country: "Solomon Islands" },
  { country_id: "218", Country: "Somalia" },
  { country_id: "219", Country: "South Africa" },
  { country_id: "220", Country: "South Ossetia" },
  { country_id: "221", Country: "South Sudan" },
  { country_id: "222", Country: "Spain" },
  { country_id: "223", Country: "St. Pierre & Miquelon" },
  { country_id: "224", Country: "Sudan" },
  { country_id: "225", Country: "Svalbard & Jan Mayen Islands" },
  { country_id: "226", Country: "Eswatini" },
  { country_id: "227", Country: "Sweden" },
  { country_id: "228", Country: "Switzerland" },
  { country_id: "229", Country: "Syria (Syrian Arab Republic)" },
  { country_id: "230", Country: "Tajikistan" },
  { country_id: "231", Country: "Tibet" },
  { country_id: "232", Country: "Trinidad & Tobago" },
  { country_id: "233", Country: "Tunisia" },
  { country_id: "234", Country: "Türkiye" },
  { country_id: "235", Country: "Turks & Caicos Islands" },
  { country_id: "236", Country: "Uganda" },
  { country_id: "237", Country: "Ukraine" },
  { country_id: "238", Country: "United Arab Emirates" },
  { country_id: "239", Country: "United Kingdom" },
  { country_id: "240", Country: "United States of America" },
  { country_id: "241", Country: "Uzbekistan" },
  { country_id: "242", Country: "Vatican City State (Holy See)" },
  { country_id: "243", Country: "Viet Nam" },
  { country_id: "244", Country: "Virgin Islands (British)" },
  { country_id: "245", Country: "Virgin Islands (US)" },
  { country_id: "246", Country: "Wallis and Futuna Islands" },
  { country_id: "247", Country: "Western Sahara" },
  { country_id: "248", Country: "Yemen" },
  { country_id: "249", Country: "Åland Islands" },
  { country_id: "250", Country: "British Indian Ocean Territory" },
  { country_id: "251", Country: "French Southern Territories" },
  { country_id: "252", Country: "United States Minor Outlying Islands" }
];

// 产品ID数据 (从CSV文件导入)
export const productIdData = [
  { url: "1", product: "Animal and vegetable oils, fats and waxes" },
  { url: "2", product: "Fixed vegetable fats and oils" },
  { url: "3", product: "Other vegetable oils and fats" },
  { url: "4", product: "Palm oil" },
  { url: "5", product: "Soy oil" },
  { url: "6", product: "Animal oils and fats" },
  { url: "7", product: "Processed animal or vegetable fats, oils and waxes (non edible)" },
  { url: "8", product: "Beverages and tobacco" },
  { url: "9", product: "Tobacco and tobacco manufactures" },
  { url: "10", product: "Tobacco (manufactured, also tobacco substitutes)" },
  { url: "11", product: "Tobacco (unmanufactured) and tobacco refuse" },
  { url: "12", product: "Beverages" },
  { url: "13", product: "Non alcoholic beverages (natural/mineral water, soda)" },
  { url: "14", product: "Alcoholic beverages (a.o. beer, wine, liquor/liqueur, distilled)" },
  { url: "15", product: "Chemicals and related products" },
  { url: "16", product: "Plastics in nonprimary forms" },
  { url: "17", product: "Plates, sheets, film, foil and strips of plastics" },
  { url: "18", product: "Monofilament, rods, sticks and profile shapes of plastics" },
  { url: "19", product: "Tubes, pipes and hoses of plastics" },
  { url: "20", product: "Plastics in primary forms" },
  { url: "21", product: "Other plastics (in primary forms)" },
  { url: "22", product: "Polymers of ethylene (in primary forms)" },
  { url: "23", product: "Polyacetals, polyethers and epoxide resins (in primary forms)" },
  { url: "24", product: "Polymers of styrene (in primary forms)" },
  { url: "25", product: "Polymers of vinyl chloride or other halogenated olefins (in primary forms)" },
  { url: "26", product: "Waste, parings and scrap of plastics" },
  { url: "27", product: "Organic chemicals" },
  { url: "28", product: "Other organic chemicals" },
  { url: "29", product: "Organo-inorganic compounds, heterocyclic compounds, nucleic acids and their salts" },
  { url: "30", product: "Alcohols, phenols and derivatives" },
  { url: "31", product: "Nitrogen-function compounds" },
  { url: "32", product: "Hydrocarbons and derivatives" },
  { url: "33", product: "Medicinal and pharmaceutical products" },
  { url: "34", product: "Soap, cleansing and polishing preparations" },
  { url: "35", product: "Medicinal and pharmaceutical products (no medicaments)" },
  { url: "36", product: "Medicaments (including veterinary medicaments)" },
  { url: "37", product: "Chemical materials and products" },
  { url: "38", product: "Explosives and pyrotechnic products" },
  { url: "39", product: "Insecticides, fungicides, herbicides and disinfectants" },
  { url: "40", product: "Lubricants, liquids for hydraulic transmissions, antifreezes and deicing fluids" },
  { url: "41", product: "Miscellaneous chemical products" },
  { url: "42", product: "Starches, inulin and wheat gluten, albuminoidal substances and glues" },
  { url: "43", product: "Carboxylic acids and derivatives" },
  { url: "44", product: "Essential oils, perfumes and soaps" },
  { url: "45", product: "Essential oils, perfume and flavor materials" },
  { url: "46", product: "Perfumery, cosmetics, or toilet preparations (no soaps)" },
  { url: "47", product: "Inorganic chemicals" },
  { url: "48", product: "Radioactive and associated materials" },
  { url: "49", product: "Inorganic chemical elements, oxides and halogen salts (incl. silicon)" },
  { url: "50", product: "Metallic salts and peroxysalts of inorganic acids" },
  { url: "51", product: "Inorganic chemicals and compounds of precious metals" },
  { url: "52", product: "Fertilizers" },
  { url: "53", product: "Dyeing, tanning and coloring materials" },
  { url: "54", product: "Synthetic organic varnishes, dyes and color lakes" },
  { url: "55", product: "Dyeing and tanning extracts, and synthetic tanning materials" },
  { url: "56", product: "Pigments, paints, varnishes and related materials" },
  { url: "57", product: "Manufactured goods classified chiefly by material" },
  { url: "58", product: "Textile yarn and fabrics" },
  { url: "59", product: "Woven fabrics of other textile materials (including narrow or special fabrics)" },
  { url: "60", product: "Knitted or crocheted fabrics" },
  { url: "61", product: "Textile yarn" },
  { url: "62", product: "Woven fabrics of synthetic textile materials" },
  { url: "63", product: "Cotton fabrics (woven)" },
  { url: "64", product: "Made-up articles, wholly or chiefly of textile materials" },
  { url: "65", product: "Special yarns and special textile fabrics" },
  { url: "66", product: "Tulles, lace, embroidery, ribbons, trimmings and other small wares" },
  { url: "67", product: "Floor coverings, carpets and linoleum" },
  { url: "68", product: "Non-metallic mineral manufactures" },
  { url: "69", product: "Lime, cement, and fabricated construction materials (not glass or clay)" },
  { url: "70", product: "Mineral manufactures such as concrete (not clay or glass)" },
  { url: "71", product: "Household ceramics and porcelain" },
  { url: "72", product: "Glassware" },
  { url: "73", product: "Clay construction materials & refractory construction materials (roof tiles, bricks)" },
  { url: "74", product: "Pearls, precious and semiprecious stones (unworked or worked)" },
  { url: "75", product: "Glass" },
  { url: "76", product: "Iron and steel" },
  { url: "77", product: "Iron and steel tubes, pipes and hollow profiles, fittings for tubes and pipes" },
  { url: "78", product: "Alloy steel flat-rolled products" },
  { url: "79", product: "Iron and nonalloy steel flat-rolled products (clad, plated or coated)" },
  { url: "80", product: "Iron or nonalloy steel flat-rolled products (not clad, plated or coated)" },
  { url: "81", product: "Pig iron and spiegeleisen, sponge iron, iron or steel granules and powders and ferroalloys" },
  { url: "82", product: "Iron and steel wire" },
  { url: "83", product: "Iron or steel ingots and other primary forms, and semifinished products of iron or steel" },
  { url: "84", product: "Iron and steel rails and railway track construction material" },
  { url: "85", product: "Iron and steel bars, rods, angles, shapes and sections, including sheet piling" },
  { url: "86", product: "Paper, paperboard, paper pulp and articles thereof" },
  { url: "87", product: "Articles of paper and paperboard (including diapers)" },
  { url: "88", product: "Paper and paperboard (sheets)" },
  { url: "89", product: "Sanitary napkins and tampons, diapers, and similar sanitary articles" },
  { url: "90", product: "Rubber manufactures" },
  { url: "91", product: "Rubber tires, interchangeable tire treads, tire flaps and inner tubes" },
  { url: "92", product: "Materials of rubber (pastes, plates, sheets, rods, thread, tubes, etc.)" },
  { url: "93", product: "Articles of rubber" },
  { url: "94", product: "Nonferrous metals" },
  { url: "95", product: "Silver, platinum and other platinum group metals (including palladium)" },
  { url: "96", product: "Zinc and zinc alloys" },
  { url: "97", product: "Tin and tin alloys" },
  { url: "98", product: "Miscellaneous nonferrous base metals and alloys (including coltan)" },
  { url: "99", product: "Copper and copper alloys" },
  { url: "100", product: "Lead and lead alloys" },
  { url: "101", product: "Gold, nonmonetary" },
  { url: "102", product: "Nickel and nickel alloys" },
  { url: "103", product: "Aluminum and aluminum alloys" },
  { url: "104", product: "Leather and leather manufactures" },
  { url: "105", product: "Furskins, tanned or dressed (no fake furs or fur articles)" },
  { url: "106", product: "Leather" },
  { url: "107", product: "Manufactures of leather or composition leather (including saddlery and harnesses)" },
  { url: "108", product: "Cork and wood manufactures, no furniture" },
  { url: "109", product: "Wood manufactures (no furniture)" },
  { url: "110", product: "Cork manufactures" },
  { url: "111", product: "Worked wood (veneers, plywood, particle boards)" },
  { url: "112", product: "Manufactures of metals" },
  { url: "113", product: "Wire products (excluding insulated electrical wiring) and fencing grills" },
  { url: "114", product: "Household equipment of base metal" },
  { url: "115", product: "Other manufactures of base metal" },
  { url: "116", product: "Nails, screws, nuts, bolts, rivets and similar articles" },
  { url: "117", product: "Tools for use in the hand or in machines" },
  { url: "118", product: "Metal structures and parts of iron, steel or aluminum" },
  { url: "119", product: "Metal containers for storage or transport" },
  { url: "120", product: "Cutlery and tableware (knives, spoons, forks, etc.)" },
  { url: "121", product: "Machinery and transport equipment" },
  { url: "122", product: "Metalworking machinery" },
  { url: "123", product: "Metalworking machinery (other than machine tools) and parts thereof" },
  { url: "124", product: "Machine parts and accessories, and hand held tool holders" },
  { url: "125", product: "Machine tools for working metal, sintered metal carbides or cermets" },
  { url: "126", product: "Machine tools working by removing metal or other materials" },
  { url: "127", product: "Office machines and automatic data processing machines" },
  { url: "128", product: "Parts and accessories for office machines and computers" },
  { url: "129", product: "Computers and computer-related machinery (including laptops, notebooks, ipads and other tablets)" },
  { url: "130", product: "Office machines (not computers)" },
  { url: "131", product: "Telecommunications machines and (consumer) electronics" },
  { url: "132", product: "Radio-broadcast receivers" },
  { url: "133", product: "Telecommunications equipment, telephones, mobile and smartphones (including parts & accessories)" },
  { url: "134", product: "Tv receivers, video monitors and projectors, video/dvd recording (electronics)" },
  { url: "135", product: "Sound & television recorders or reproducers" },
  { url: "136", product: "Road vehicles" },
  { url: "137", product: "Other road motor vehicles" },
  { url: "138", product: "Motor vehicles for the transport of goods and special purpose motor vehicles" },
  { url: "139", product: "Motor cars and other motor vehicles for the transport of persons (not public transport)" },
  { url: "140", product: "Parts and accessories for tractors, motor cars, trucks, public-transport/road motor vehicles" },
  { url: "141", product: "Motorcycles (including mopeds) and cycles, motorized and not motorized, invalid carriages" },
  { url: "142", product: "Trailers and semi-trailers, not mechanically propelled vehicles and transport containers" },
  { url: "143", product: "Power generating machinery and equipment" },
  { url: "144", product: "Rotating electric machines (and parts thereof)" },
  { url: "145", product: "Power/electricity generating machinery and parts thereof (incl. solar panels, wind turbines etc.)" },
  { url: "146", product: "Steam or other vapor generating boilers and super-heated water boilers (and parts thereof)" },
  { url: "147", product: "Steam turbines and other vapor turbines (and parts thereof)" },
  { url: "148", product: "Engines and motors, nonelectric (and parts thereof)" },
  { url: "149", product: "Internal combustion piston engines (and parts thereof)" },
  { url: "150", product: "Electrical machinery, apparatus and electronics (and parts thereof)" },
  { url: "151", product: "Thermionic valves/tubes, diodes, transistors and similar semiconductor devices/integrated circuits" },
  { url: "152", product: "Electrical apparatus for switching, protecting or connecting electrical circuits" },
  { url: "153", product: "Electro-diagnostic apparatus for medical sciences and radiological apparatus" },
  { url: "154", product: "Other electrical machinery and apparatus (electronics)" },
  { url: "155", product: "Household type electrical and nonelectrical equipment (electronics)" },
  { url: "156", product: "Equipment for distributing electricity" },
  { url: "157", product: "Electric power machinery (not rotating electric power generating machinery) and parts thereof" },
  { url: "158", product: "Machinery specialized for particular industries" },
  { url: "159", product: "Tractors (other than mechanical handling equipment)" },
  { url: "160", product: "Food-processing machines (excluding domestic)" },
  { url: "161", product: "Textile and leather machinery (and parts thereof)" },
  { url: "162", product: "Agricultural machinery, excluding tractors (and parts thereof)" },
  { url: "163", product: "Machinery and equipment specialized for particular industries (and parts thereof)" },
  { url: "164", product: "Printing and bookbinding machinery (and parts thereof)" },
  { url: "165", product: "Paper mill and pulp mill machinery, paper cutting machines (and parts thereof)" },
  { url: "166", product: "Civil engineering and contractors' plant and equipment" },
  { url: "167", product: "Transport equipment" },
  { url: "168", product: "(Parts of) aircraft (equipment), spacecraft, satellites and spacecraft launch vehicles" },
  { url: "169", product: "Ships, boats (including hovercraft) and floating structures" },
  { url: "170", product: "Railway vehicles (including hovertrains) and associated equipment" },
  { url: "171", product: "General industrial machinery and equipment" },
  { url: "172", product: "Heating and cooling equipment (and parts thereof)" },
  { url: "173", product: "Pumps for liquids, liquid elevators (and parts thereof)" },
  { url: "174", product: "Taps, cocks, valves and similar appliances for pipes, boiler shells and tanks" },
  { url: "175", product: "Ball or roller bearings" },
  { url: "176", product: "Mechanical handling equipment (and parts thereof)" },
  { url: "177", product: "Nonelectric parts and accessories of machinery" },
  { url: "178", product: "(Parts of) transmission shafts/cranks, shaft bearings (housing), gearing, ball screws, clutches" },
  { url: "179", product: "Pumps (not for liquids), air or gas compressors and fans, centrifuges (and parts thereof)" },
  { url: "180", product: "Nonelectrical machinery, tools and mechanical apparatus (and parts thereof)" },
  { url: "181", product: "Crude materials inedible, except fuels" },
  { url: "182", product: "Metalliferous ores and metal scrap" },
  { url: "183", product: "Iron ore and concentrates" },
  { url: "184", product: "Nickel ores and concentrates (including nickel mattes, nickel oxide sinters)" },
  { url: "185", product: "Nonferrous base metal waste and scrap" },
  { url: "186", product: "Ores and concentrates of base metals (incl. lead, tin, tantalum, tungsten, niobium, chromium, zinc)" },
  { url: "187", product: "Ferrous waste and scrap (including remelting ingots of iron or steel)" },
  { url: "188", product: "Copper ores and concentrates (including copper mattes, cement copper)" },
  { url: "189", product: "Aluminum ores and concentrates (including alumina)" },
  { url: "190", product: "Ores and concentrates of uranium or thorium" },
  { url: "191", product: "Ores and waste of precious metals (other than of gold)" },
  { url: "192", product: "Pulp and waste paper" },
  { url: "193", product: "Raw hides and skins" },
  { url: "194", product: "Raw furskins" },
  { url: "195", product: "Raw hides and skins (except furskins)" },
  { url: "196", product: "Oil seeds and oleaginous fruits" },
  { url: "197", product: "Soy beans" },
  { url: "198", product: "Peanuts" },
  { url: "199", product: "Palm nuts" },
  { url: "200", product: "Cotton seed" },
  { url: "201", product: "Mustard seed" },
  { url: "202", product: "Oil-seeds & oleaginous fruits, n.e.s." },
  { url: "203", product: "Crude rubber" },
  { url: "204", product: "Natural rubber (including latex, balata, gutta-percha, guayule, chicle and similar natural gums)" },
  { url: "205", product: "Synthetic rubber, reclaimed rubber and waste of unhardened rubber" },
  { url: "206", product: "Crude animal and vegetable materials" },
  { url: "207", product: "Bamboo, rattan, reeds, straw, etc." },
  { url: "208", product: "Bulbs, tubers and (parts of) live plants" },
  { url: "209", product: "Crude animal materials (such as ivory, coral, hair, bones, feathers)" },
  { url: "210", product: "Cut flowers and foliage" },
  { url: "211", product: "Lac, natural gums, resins, gum resins, and balsams" },
  { url: "212", product: "Seeds, fruit and spores used for sowing" },
  { url: "213", product: "Liquorice and ginseng" },
  { url: "214", product: "Other materials of vegetable origin" },
  { url: "215", product: "Seaweed" },
  { url: "216", product: "Cork and wood" },
  { url: "217", product: "Wood in the rough or roughly squared" },
  { url: "218", product: "Wood in chips or particles, and wood waste" },
  { url: "219", product: "Fuel wood (excluding wood waste), and wood charcoal" },
  { url: "220", product: "Raw natural cork and waste of natural cork" },
  { url: "221", product: "Wood (simply worked) and railway sleepers of wood" },
  { url: "222", product: "Crude fertilizers and crude minerals" },
  { url: "223", product: "Sulfur and unroasted iron pyrites" },
  { url: "224", product: "Crude fertilizers" },
  { url: "225", product: "Crude minerals (e.g. clays, salt, asbestos, bitumen)" },
  { url: "226", product: "Natural abrasives (including industrial diamonds)" },
  { url: "227", product: "Stone, sand and gravel" },
  { url: "228", product: "Textile fibers and their wastes" },
  { url: "229", product: "Wool and other animal hair (including wool tops)" },
  { url: "230", product: "Worn clothing and rags" },
  { url: "231", product: "Synthetic fibers suitable for spinning" },
  { url: "232", product: "Silk textile fibers" },
  { url: "233", product: "Cotton textile fibers" },
  { url: "234", product: "Jute and other textile bast fibers" },
  { url: "235", product: "Manmade fibers suitable for spinning" },
  { url: "236", product: "Other vegetable textile fibers (hemp, sisal, cocos, flax, etc.)" },
  { url: "237", product: "Mineral fuels and lubricants" },
  { url: "238", product: "Biofuels" },
  { url: "239", product: "Coal, coke and briquettes" },
  { url: "240", product: "Briquettes, lignite and peat" },
  { url: "241", product: "Coal (not agglomerated)" },
  { url: "242", product: "Coke and semicoke (including char) and retort carbon" },
  { url: "243", product: "Petroleum and petroleum products" },
  { url: "244", product: "Petroleum oils and oils from bituminous minerals (other than crude)" },
  { url: "245", product: "Residual petroleum products" },
  { url: "246", product: "Crude petroleum oils and oils from bituminous minerals" },
  { url: "247", product: "Gas, natural and manufactured" },
  { url: "248", product: "Liquefied propane and butane" },
  { url: "249", product: "Coal gas, water gas, producer gas and similar gases" },
  { url: "250", product: "Natural gas (whether or not liquified)" },
  { url: "251", product: "Petroleum gases and other gaseous hydrocarbons" },
  { url: "252", product: "Electrical energy (electric current)" },
  { url: "253", product: "Miscellaneous manufactured articles" },
  { url: "254", product: "Musical instruments and accessories, records, tapes, CDs and other sound recordings" },
  { url: "255", product: "Photographic apparatus, optical goods, watches and clocks" },
  { url: "256", product: "Cinematographic film, exposed and developed" },
  { url: "257", product: "Optical goods, lenses and glasses" },
  { url: "258", product: "Photographic and cinematographic supplies" },
  { url: "259", product: "Photographic apparatus and equipment" },
  { url: "260", product: "Watches and clocks" },
  { url: "261", product: "Furniture and parts thereof, bedding" },
  { url: "262", product: "Manufactured goods" },
  { url: "263", product: "Works of art, collectors' pieces and antiques" },
  { url: "264", product: "Footwear and shoes" },
  { url: "265", product: "Umbrellas, parasols, walking-sticks" },
  { url: "266", product: "Arms and ammunition" },
  { url: "267", product: "Travel goods and handbags" },
  { url: "268", product: "Orthopedic and medical appliances, artifical body parts, hearing aids" },
  { url: "269", product: "Prefabricated buildings, sanitary and lighting" },
  { url: "270", product: "Prefabricated buildings" },
  { url: "271", product: "Sanitary, plumbing and heating fixtures and fittings" },
  { url: "272", product: "Lighting fixtures and fittings" },
  { url: "273", product: "Candles, matches, articles of combustible materials, smokers' requisites" },
  { url: "274", product: "Basketware, wickerwork, brooms, brushes etc" },
  { url: "275", product: "Articles and manufactures of carving or molding materials" },
  { url: "276", product: "Articles of plastics" },
  { url: "277", product: "Printed matter, books and magazines" },
  { url: "278", product: "Articles of apparel and clothing accessories" },
  { url: "279", product: "Clothing accessories, of textile fabrics" },
  { url: "280", product: "Clothes of woven textiles (except swimwear and coated or laminated apparel)" },
  { url: "281", product: "Clothing of knitted or crocheted textile fabric (except swimwear or coated apparel)" },
  { url: "282", product: "Other articles of apparel of textile fabrics (also baby clothing)" },
  { url: "283", product: "Apparel and clothing accessories of other than textile fabrics, and headgear, fur, leather" },
  { url: "284", product: "Baby carriages, toys, games and sporting goods" },
  { url: "285", product: "Festive, Carnival or other entertainment articles" },
  { url: "286", product: "Jewelry, goldsmiths' and silversmiths' ware" },
  { url: "287", product: "Office and stationery supplies" },
  { url: "288", product: "Professional and scientific instruments and apparatus" },
  { url: "289", product: "Instruments for medical, surgical, dental or veterinary purposes, healthcare equipment" },
  { url: "290", product: "Meters and counters" },
  { url: "291", product: "Measuring, checking, analysing and controlling instruments and apparatus" },
  { url: "292", product: "Optical instruments and apparatus" },
  { url: "293", product: "Services" },
  { url: "294", product: "Business services" },
  { url: "295", product: "Holdings (non financial), group services and management advisory" },
  { url: "296", product: "Other business services" },
  { url: "297", product: "Legal services, accountancy, tax advisory and administration" },
  { url: "298", product: "Facility management, cleaning & landscape services" },
  { url: "299", product: "Security & investigation" },
  { url: "300", product: "Job placement & employment agencies" },
  { url: "301", product: "Advertising & market research" },
  { url: "302", product: "Research & development services" },
  { url: "303", product: "Design, photography, translation and other consultancy" },
  { url: "304", product: "Transport and storage (incl. mail and deliverers)" },
  { url: "305", product: "Tourism & catering" },
  { url: "306", product: "Construction" },
  { url: "307", product: "Mining and quarrying" },
  { url: "308", product: "Agriculture, hunting, forestry and fishing" },
  { url: "309", product: "Water, waste and recycling" },
  { url: "310", product: "Energy production, distribution and trade" },
  { url: "311", product: "Government, education & health care" },
  { url: "312", product: "Repair & installation of machinery and equipment" },
  { url: "313", product: "Arts, culture, sport & leisure" },
  { url: "314", product: "Media, ICT and telecom" },
  { url: "315", product: "Financial services" },
  { url: "316", product: "Rental and lease" },
  { url: "317", product: "Food and live animals" },
  { url: "318", product: "Dairy products and birds' eggs" },
  { url: "319", product: "Milk and cream and milk products (other than butter or cheese)" },
  { url: "320", product: "Birds' eggs, egg yolks and egg albumin (fresh, dried or otherwise preserved)" },
  { url: "321", product: "Cheese and curd" },
  { url: "322", product: "Butter and other fats derived from milk" },
  { url: "323", product: "Fish and crustaceans" },
  { url: "324", product: "Fish, crustaceans, molluscs and other aquatic invertebrates (prepared or preserved)" },
  { url: "325", product: "Crustaceans & molluscs" },
  { url: "326", product: "Fish (dried, salted or smoked) or fish meal & flour" },
  { url: "327", product: "Fish (fresh, chilled or frozen)" },
  { url: "328", product: "Meat and meat preparations" },
  { url: "329", product: "Meat of bovine animals (fresh, chilled or frozen)" },
  { url: "330", product: "Meat and edible meat offal (salted, in brine, dried or smoked)" },
  { url: "331", product: "Meat and edible meat offal (prepared or preserved)" },
  { url: "332", product: "Other meat (not bovine) and edible meat offal (fresh, chilled or frozen)" },
  { url: "333", product: "Live animals" },
  { url: "334", product: "Bovine animals, live" },
  { url: "335", product: "Horses, donkeys, mules and hinnies, live" },
  { url: "336", product: "Other live animals" },
  { url: "337", product: "Swine, live" },
  { url: "338", product: "Sheep and goats, live" },
  { url: "339", product: "Poultry, live" },
  { url: "340", product: "Cereals and cereal preparations" },
  { url: "341", product: "Cereal preparations and preparations of flour or starch of fruits or vegetables" },
  { url: "342", product: "Cereal meals and flours" },
  { url: "343", product: "Barley (unmilled)" },
  { url: "344", product: "Maize (not sweet corn, unmilled)" },
  { url: "345", product: "Meal and flour of wheat and meslin" },
  { url: "346", product: "Wheat, spelt and meslin (unmilled)" },
  { url: "347", product: "Rice" },
  { url: "348", product: "Other cereals (unmilled)" },
  { url: "349", product: "Coffee, tea, cocoa and spices" },
  { url: "350", product: "Ginger, curcuma or turmeric (excluding ginger preserved in sugar or conserved in syrup)" },
  { url: "351", product: "Pepper, chili, bell pepper" },
  { url: "352", product: "Coffee and coffee substitutes" },
  { url: "353", product: "Cocoa" },
  { url: "354", product: "Cloves (whole fruit, cloves and stems)" },
  { url: "355", product: "Seeds of anise, badian, fennel, coriander, cumin or caraway, juniper berries" },
  { url: "356", product: "Spices" },
  { url: "357", product: "Vanilla (beans)" },
  { url: "358", product: "Tea and mate (including coca, khat/qat/miraa)" },
  { url: "359", product: "Cinnamon and cinnamon-tree flowers" },
  { url: "360", product: "Chocolate and other cocoa preparations" },
  { url: "361", product: "Vegetables and fruit" },
  { url: "362", product: "Onions and shallots, fresh or chilled" },
  { url: "363", product: "Oranges, fresh or dried" },
  { url: "364", product: "Fruit and vegetable juices, unfermented (including grape must)" },
  { url: "365", product: "Mushrooms and truffles, fresh or chilled" },
  { url: "366", product: "Melons (including watermelons) and papaws (papayas), fresh" },
  { url: "367", product: "Other fresh fruit" },
  { url: "368", product: "Other edible nuts" },
  { url: "369", product: "Roots and tubers, for human food, fresh or dried (sugar cane, sugar beet, cassave)" },
  { url: "370", product: "Potatoes, fresh or chilled (not including sweet potatoes)" },
  { url: "371", product: "Pineapples, fresh or dried" },
  { url: "372", product: "Pears and quinces, fresh" },
  { url: "373", product: "Lettuce and chicory (including endive), fresh or chilled" },
  { url: "374", product: "Leguminous vegetables, dried, shelled (beans)" },
  { url: "375", product: "Cashew nuts, fresh or dried" },
  { url: "376", product: "Citrus fruit, fresh or dried" },
  { url: "377", product: "Carrots, turnips, beetroot, salsify, celeriac, radishes, similar edible roots, fresh or chilled" },
  { url: "378", product: "Cabbage and similar edible brassicas (broccoli, cauliflower)" },{ url: "379", product: "Berries, fresh" },
  { url: "380", product: "Coconuts, fresh or dried" },
  { url: "381", product: "Cucumbers and gherkins, fresh or chilled" },
  { url: "382", product: "Hazelnuts or filberts, fresh or dried" },
  { url: "383", product: "Grapes, fresh or dried" },
  { url: "384", product: "Garlic, leeks and other alliaceous vegetables, fresh or chilled" },
  { url: "385", product: "Dates, fresh or dried" },
  { url: "386", product: "Stone Fruit, fresh (e.g. cherries, peaches, apricots, nectarines)" },
  { url: "387", product: "Sweet corn (uncooked or cooked by steaming or boiling in water), frozen" },
  { url: "388", product: "Figs, fresh or dried" },
  { url: "389", product: "Tomatoes, fresh or chilled" },
  { url: "390", product: "Preserved vegetables and vegetables preparations" },
  { url: "391", product: "Preserved fruit and fruit preparations (excluding fruit juices)" },
  { url: "392", product: "Almonds, fresh or dried" },
  { url: "393", product: "Apples, fresh" },
  { url: "394", product: "Apricot, peach or plum stones and kernels, fresh or dried, whether or not ground" },
  { url: "395", product: "Bananas (including plantains), fresh or dried" },
  { url: "396", product: "Avocados, guavas, mangoes and mangosteens, fresh or dried" },
  { url: "397", product: "Aubergines, (eggplant), fresh or chilled" },
  { url: "398", product: "Arrowroot, salep, jerusalem artichokes, sweet potatoes, similar roots and tubers, fresh or dried" },
  { url: "399", product: "Miscellaneous edible products and preparations of food" },
  { url: "400", product: "Edible products and preparations of food" },
  { url: "401", product: "Margarine and shortening" },
  { url: "402", product: "Feeding stuff for cattle and other animals (cattle, fish)" },
  { url: "403", product: "Residues of starch manufacture, beet-pulp, bagasse and waste of food industry" },
  { url: "404", product: "Bran, sharps and other residues from cereals or leguminous plants" },
  { url: "405", product: "Food wastes & prepared animal feeds (incl. dog & cat food)" },
  { url: "406", product: "Food for pets" },
  { url: "407", product: "Flours, meals, pellets & greaves of meat (incl. meat offal, fish, crustaceans, molluscs)" },
  { url: "408", product: "Hay and fodder (of cereals or leguminous plants)" },
  { url: "409", product: "Sugars, sugar preparations & honey" },
  { url: "410", product: "Natural Honey" },
  { url: "411", product: "Cane sugar, raw or processed" },
  { url: "412", product: "Beet sugar, raw or processed" },
  { url: "413", product: "Other sugars (including chemically pure lactose, maltose, glucose and fructose); sugar syrups; artificial honey; caramel" },
  { url: "414", product: "Sugar confectionary (candy, chewing gum)" },
  { url: "415", product: "Growing of food crops" },
  { url: "416", product: "Arts" },
  { url: "417", product: "Lending of cultural goods, public archives, museums, botanical and zoological gardens and nature reserves activities" },
  { url: "418", product: "Growing of ornamental plants" },
  { url: "419", product: "Lotteries and betting" },
  { url: "420", product: "Animal breeding and husbandry" },
  { url: "421", product: "Sports and recreation" },
  { url: "422", product: "Support activities to agriculture (incl. treatment of crops and seeds)" },
  { url: "423", product: "Public administration, public services and compulsory social security" },
  { url: "424", product: "Hunting" },
  { url: "425", product: "Education" },
  { url: "426", product: "Forestry and logging" },
  { url: "427", product: "Support activities to forestry" },
  { url: "428", product: "Health care" },
  { url: "429", product: "Fishing" },
  { url: "430", product: "Aquaculture" },
  { url: "431", product: "Residential care activities" },
  { url: "432", product: "Social work activities without accommodation" },
  { url: "433", product: "Extraction of crude petroleum and natural gas" },
  { url: "434", product: "Mining and quarrying (no oil and gas)" },
  { url: "435", product: "Mining support activities" },
  { url: "436", product: "Publishing of books, magazines etc." },
  { url: "437", product: "Software publishing" },
  { url: "438", product: "Motion picture, video and television programme production" },
  { url: "439", product: "Sound recording and music publishing activities" },
  { url: "440", product: "Programming and broadcasting activities (radio and television)" },
  { url: "441", product: "Financial institutions (except insurance and pension funds)" },
  { url: "442", product: "Telecommunications" },
  { url: "443", product: "Insurance and pension funding (not compulsory social insurance)" },
  { url: "444", product: "Support activities in the field of information technology" },
  { url: "445", product: "Other financial services" },
  { url: "446", product: "Information service activities" },
  { url: "447", product: "Travel agency, tour operator, tourist information and reservation services" },
  { url: "448", product: "Repair of metal products, machinery and equipment" },
  { url: "449", product: "Accommodation services (incl. housekeeping)" },
  { url: "450", product: "Installation of industrial machinery and equipment" },
  { url: "451", product: "Food and beverage service activities" },
  { url: "452", product: "Repair of computers and communication equipment" },
  { url: "453", product: "Repair of computers and peripheral equipment" },
  { url: "454", product: "Land transport (incl. transport via pipeline)" },
  { url: "455", product: "Production of electricity" },
  { url: "456", product: "Water transport" },
  { url: "457", product: "Operation of transmission systems for electricity, gas and hot water" },
  { url: "458", product: "Air transport" },
  { url: "459", product: "Distribution of electricity and gas through pipes" },
  { url: "460", product: "Warehousing and support activities for transportation" },
  { url: "461", product: "Trade of electricity and gas through pipes" },
  { url: "462", product: "Postal and courier activities" },
  { url: "463", product: "Manufacture of gas" },
  { url: "464", product: "Steam and air conditioning supply" },
  { url: "465", product: "Renting, buying and selling of real estate" },
  { url: "466", product: "Renting of movable property" },
  { url: "467", product: "Collection, purification and distribution of water" },
  { url: "468", product: "Construction of buildings and development of building projects" },
  { url: "469", product: "Sewerage" },
  { url: "470", product: "Civil engineering (excl. earthworks)" },
  { url: "471", product: "Specialised construction activities" },
  { url: "472", product: "Waste collection, treatment and disposal activities" },
  { url: "473", product: "Recycling (incl. preparation for recycling)" },
  { url: "474", product: "Remediation activities and other waste management services" },
  { url: "475", product: "" },
  { url: "476", product: "Technical testing and analysis" },
  { url: "477", product: "Veterinary activities" },
];

// 获取国家ID
export const getCountryId = (countryName: string): string => {
  //const cleanedCountry = cleanName(countryName);
  const country = countryIdData.find(item => 
    item.Country === countryName
  );
 //(countryName, country?.country_id)
  return country?.country_id || "";
};

// 获取产品ID
export const getProductId = (productName: string): string => {
  //const cleanedInput = cleanName(productName);
  const product = productIdData.find(item => 
    item.product === productName
  );
  //console.log(productName, product?.url)
  return product?.url || "";
};

// 构建爬取URL
/* ========= 修改 1：构建上游 URL —— 只编码一次 ========= */
export const buildScrapeUrl = (productId: string, countryId: string): string => {
  const u = new URL('https://www.mvorisicochecker.nl/en/csr-risiko-check-extern');
  u.searchParams.append('products[]', productId);
  u.searchParams.append('countries[]', countryId);
  u.searchParams.append('email', '');
  u.searchParams.append('data_protect', '1');
  return u.toString(); // -> 自动得到 products%5B%5D & countries%5B%5D
};

// 爬取目标URL内容的函数 - 使用本地代理服务器
/* ========= 修改 2：通过本地/同源代理抓取 ========= */
export const scrapeUrlContent = async (targetUrl: string, retryCount = 3): Promise<string> => {
  const { type, base } = getBackendBase();

  // 生成代理请求地址
  // same-origin 情况：/proxy?url=...
  // absolute 情况：  http://<host>:3001/proxy?url=...
  const proxyUrl = new URL(type === 'same-origin' ? base : `${base}/proxy`, window.location.origin);
  proxyUrl.searchParams.set('url', targetUrl); // 只包一层 encode（不会产生 %255B%255D）
  console.log('[scrape] request', { proxy: proxyUrl.toString(), targetUrl });

  // 简单超时控制
  const timeoutMs = 15000;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const resp = await fetch(proxyUrl.toString(), {
      method: 'GET',
      headers: {
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Cache-Control': 'no-cache'
      },
      signal: controller.signal,
    });

    if (!resp.ok) {
      throw new Error(`HTTP ${resp.status}: ${resp.statusText}`);
    }

    const html = await resp.text();
    console.log('[scrape] response', { ok: resp.ok, status: resp.status, length: html.length });
    if (!html || html.length < 100) {
      throw new Error('Empty or invalid content received');
    }
    return html;
  } catch (err) {
    if (retryCount > 0) {
      // 指数退避：2s, 4s, 6s...
      const attempt = 4 - retryCount;
      await new Promise(r => setTimeout(r, 2000 * attempt));
      return scrapeUrlContent(targetUrl, retryCount - 1);
    }
    // 这里返回 HTML 片段给页面展示错误（维持你的原行为）
    return `
      <div class="error-message bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
        <p>Failed to load risk assessment data. Please try again later.</p>
        <p class="text-sm mt-1">Error: ${err instanceof Error ? err.message : String(err)}</p>
        <p class="text-sm mt-1">Proxy: ${type === 'same-origin' ? base : `${base}/proxy`}</p>
        <p class="text-sm mt-1">Target: ${targetUrl}</p>
      </div>
    `;
  } finally {
    clearTimeout(timer);
  }
};

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
